### ISSUE TITLE
example

### ISSUE THREAD

**Issue by lanchen2019** [ftbabi/TIE_ECCV2022#1]
Hi,
Thanks for releasing your code! That's an interesting work. Could you please give an example of your experiments with data and checkpoints? Thank you so much!

**Comment by lanchen2019** [comment]
I tried to run python tools/predict_rollout.py --config configs/tie/tie_abs_boxbath.py --work_dir tie_box/ --checkpoint pretrained_model/boxbath/tie.pth  
but it prints out
OSError: PhysicsFleXDataset: Unable to open file (unable to open file: name = '/home/ydshao/Datasets/pyflex/demo/BoxBath/stat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by lanchen2019** [comment]
And when I build Pyflex I find this error  pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __powf_finite

**Comment by ftbabi** [comment]
> I tried to run python tools/predict_rollout.py --config configs/tie/tie_abs_boxbath.py --work_dir tie_box/ --checkpoint pretrained_model/boxbath/tie.pth but it prints out OSError: PhysicsFleXDataset: Unable to open file (unable to open file: name = '/home/ydshao/Datasets/pyflex/demo/BoxBath/stat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Hi lanchen,
Thanks for your interest in our project~ We upload some examples and now you can have fun~

**Comment by ftbabi** [comment]
> d symbol: __powf_finite

I think the best way is using the docker, please refer to https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md for more details.
