### ISSUE TITLE
[predict_rollout.py] How to specify the type of model to be used?

### ISSUE THREAD

**Issue by snehalstomar** [ftbabi/TIE_ECCV2022#2]
The file predict_rollout.py returns an error stating 'cfg.model doesn't exist.'  I am using the config file, 'configs/_base_/datasets/box_bath.py.'  To fix this, I added the following to predict_rollout.py: cfg['model'] = {'type':'ParticleSimulator', 'backbone':'TIE'}. However, this returns the error: TypeError: ParticleSimulator: cfg must be a dict, but got <class 'str'>. 

I am unable to infer from the model due to the error. I would be grateful if the authors could kindly provide a working inference code with appropriate setup instructions to make it work. I would appreciate help with this particular error as well.

Thanks a lot!

**Comment by ftbabi** [comment]
Hi, thanks for your interest in our work!

The "config file" for the following command:
`python tools/predict_rollout.py {CONFIG} {WORK_DIR} --checkpoint {CHECKPOINT}`
should be from "config/tie/xxx". For example, "config/tie/tie_abs_boxbath.py".

The configs in "config/_base_/" are only basic components for other models, such as "config/tie/", and cannot be used directly.

Hope this can help you.
