### ISSUE TITLE
Question about running enviroment

### ISSUE THREAD

**Issue by qingfengtommy** [ftbabi/TIE_ECCV2022#3]
Hi,

I appreciate your generosity in sharing the source code.
  
I am currently endeavoring to replicate the original datasets on a remote headless server running Linux 18.04 with Nvidia Driver, and this setup lacks physical monitors. It appears that OpenGL doesn't work in the absence of a physical screen.

Could you kindly provide more information about your server environment? Specifically, does it include a physical monitor? I am eager to determine whether it is feasible to reproduce the dataset within a screenless environment.

Best,
Tommy

**Comment by ftbabi** [comment]
Hi Tommy,

Really sorry for the late reply due my github settings.

Yes I have to use the physical monitor when generating this dataset.

Best,
Yidi

**Comment by ftbabi** [comment]
Hi Tommy,

Some more information. I follow the [original repo](https://github.com/YunzhuLi/DPI-Net) to generate the data. And I followed the one using Docker, which would use cuda9 in the docker (if I didn't remember wrong). My original desktop adopted cuda10.2 at then. And it works for me.

Best,
Yidi
